POST http://localhost:3333/events
Content-Type: application/json

{

    "title" : "Festança bacana",
    "details": "Mta putaria",
    "maximumAttendees": 100
}

####

POST http://localhost:3333/events/f7912d2f-2fc7-419f-9db1-c7d229b40a1a/attendees
Content-Type: application/json

{
    "name": "Junker",
    "email": "junker@gmail.com"
}

####

GET http://localhost:3333/events/f7912d2f-2fc7-419f-9db1-c7d229b40a1a



########

GET http://localhost:3333/attendees/3/badge


########

GET http://localhost:3333/attendees/3/check-in


########

GET http://localhost:3333/events/f7912d2f-2fc7-419f-9db1-c7d229b40a1a/attendees?query=Gustavo